### ISSUE TITLE
 ERROR open \settings.txt: The system cannot find the file specified.

### ISSUE THREAD

**Issue by wujiyu115** [ystyle/jvms#1]
环境wind764,jvms0.0.2.

安装完后打开cmd.exe出现如下错误
![Alt Text](http://ww4.sinaimg.cn/large/4b5a1116gw1f06xk0khfnj20ic073763.jpg)

**Comment by ystyle** [comment]
如果下载的是jvms-noinstall.zip, 先运行install.cmd
