### ISSUE TITLE
jvms rls 不会展示列表

### ISSUE THREAD

**Issue by ren-142326** [ystyle/jvms#16]
你好，我是java新手，我在使用jvms时，遇到了这样的问题，当我在命令行输入 jvms rls 时，控制台输出了这样的语句，

![image](https://user-images.githubusercontent.com/84454278/158352829-cca3fad3-d35f-4f41-b481-7ea56132669e.png)

我之前并没有使用过jvms 这样的工具，还希望能看到时，可以帮我解决一下，非常感谢，

**Comment by ystyle** [comment]
检查一下你控制台能不能直接访问github.  如果不能加下代理

**Comment by ren-142326** [comment]
我的控制台可以直接访问github，可以直接克隆，拉取，推送代码，
但是，当我使用jvms rls 时，还是会输出那些语句

**Comment by ystyle** [comment]
> 我的控制台可以直接访问github，可以直接克隆，拉取，推送代码， 但是，当我使用jvms rls 时，还是会输出那些语句

你试试wget 和 curl  这个地址： https://raw.githubusercontent.com/ystyle/jvms/new/jdkdlindex.json   你截图就是找不到这个地址的dns

**Comment by ren-142326** [comment]
这个地址我直接用浏览器打不开，但是我开启加速器后就可以用浏览器打开了，开启加速器终端运行也是一样的，

**Comment by ystyle** [comment]
> 这个地址我直接用浏览器打不开，但是我开启加速器后就可以用浏览器打开了，开启加速器终端运行也是一样的，

如果你加速器用的端口是8081， 你在powershell 里执行：  
```powershell
$env:http_proxy="http://127.0.0.1:8081"
$env:https_proxy="http://127.0.0.1:8081"
```
然后执行就可以了(全局的只有tun模式的才会自动代理终端， http和socket模式的只能自己设置了）
![image](https://user-images.githubusercontent.com/4478635/158427728-e29df3d9-f436-4171-a370-1b5f59df5aae.png)

ps: install 和 switch 时记得在管理员权限下打开终端

**Comment by ren-142326** [comment]
终端可以直接启用 tun 模式吗？我使用的加速器每次打开都会是不同的端口号，我是不是需要每次打开都去配置一次？

**Comment by ystyle** [comment]
> 终端可以直接启用 tun 模式吗？我使用的加速器每次打开都会是不同的端口号，我是不是需要每次打开都去配置一次？

tun模式其实就是全局代理, 像vpn那种, 会多一块虚拟网卡的
另外可以使用一些支持tun模式的转换工具, 比如netch
或者可以看看你的代理能不能设置固定端口

**Comment by ren-142326** [comment]
哦，我加速器使用的是非全局代理模式，我切换再试试，

**Comment by ren-142326** [comment]
你好，我看到的我的加速器是这样的，
![image](https://user-images.githubusercontent.com/84454278/158725166-2c0f099b-86e1-4bbd-9f46-75614d3c272e.png)
加速器运行到49895端口号下，

下面有一个说HTTP(S) 代理服务器:19180
SOCKS 代理服务器 19181

如果 我需要给终端设置代理的话，我应该怎么设置？

**Comment by ystyle** [comment]
> 你好，我看到的我的加速器是这样的， ![image](https://user-images.githubusercontent.com/84454278/158725166-2c0f099b-86e1-4bbd-9f46-75614d3c272e.png) 加速器运行到49895端口号下，
> 
> 下面有一个说HTTP(S) 代理服务器:19180 SOCKS 代理服务器 19181
> 
> 如果 我需要给终端设置代理的话，我应该怎么设置？

就用127.0.0.1:19180那个就好了. (另外win上的那个全局代理其实并不是tun模式, 它只是把IE的代理改了, 所以只有浏览器才会生效....

**Comment by ren-142326** [comment]
你好，可以了，谢谢，
![image](https://user-images.githubusercontent.com/84454278/158759463-216713b7-332e-4e10-bc03-d134080a3419.png)

**Comment by ren-142326** [comment]
你好，我本身是js使用者，java最近才开始学习，
在js这边，node版本管理工具是nvm-windows，这个工具和这个java的版本管理工具有点类似，
也都是基于go语言开发来的，
只是在版本镜像或国内代理上nvm-windows这个工具做的好一点，比较方便，
如果你这边方便的话，可以适当的进行一下优化，
最后，谢谢你的分享。

**Comment by ystyle** [comment]
> 在js这边，node版本管理工具是nvm-windows，这个工具和这个java的版本管理工具有点类似，

本来在国内有镜像的, 用的七牛, 但后来它开源也收费了, 而且得备案, 就直接用github了....
