### ISSUE TITLE
Suggestion Improvement: Allow local path for originalpath json file

### ISSUE THREAD

**Issue by TheTechOddBug** [ystyle/jvms#18]
It would be great to have the possibility to define your distribution list and storage of distributions as local path (own disk) references. In such case, you can have it locally (not requiring a server lo storage the json not the java distributions) and you can install it without connectivity.

Thanks!

**Comment by ystyle** [comment]
https://github.com/ystyle/jvms#add-a-local-jdk-version

you can copy the jdk directly to the installation directory under ` jvms/store/`
like this:
![image](https://user-images.githubusercontent.com/4478635/168569494-ce09ab53-61bf-4801-b178-715f4372e376.png)
