### ISSUE TITLE
Not working switch.

### ISSUE THREAD

**Issue by TheTechOddBug** [ystyle/jvms#19]
After installing a JDK version, I get the following error with switch and "java -version" do not found java:

![image](https://user-images.githubusercontent.com/13102096/167859594-b58361e4-d034-47c6-bf06-db9c8c6532f3.png)

**Comment by ystyle** [comment]
checks：
1. the cmd shell use administrator
2. `jvms ls` can list `OpenJDK8u-jdk_x64_windows_hotspot_8u332b09`

**Comment by erxson** [comment]
Same issue, it creates dead symlink (jvms.exe in another folder)
![image](https://user-images.githubusercontent.com/50082485/168549698-e3a53c66-2016-4c97-b736-e47c441983ad.png)

**Comment by erxson** [comment]
store folder is on desktop, not in program files

**Comment by ystyle** [comment]
@MaciejDobrowolski 
Use `jvms ls` to confirm the version is installed.
If it is manually installed locally, the confirmed directory structure is as shown in the figure
![image](https://user-images.githubusercontent.com/4478635/168568154-3fef53a4-1660-4b87-b99a-4580bd61ad0d.png)

ps: 
Upgrading to 2.1.0 fixed the installation failure

**Comment by erxson** [comment]
Fixed. Thank you!!!
