### ISSUE TITLE
exit status 1

### ISSUE THREAD

**Issue by strongant** [ystyle/jvms#3]
exit status 1: 'D:\Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

**Comment by ystyle** [comment]
在安装或解压的目录右键`install.cmd` 以管理员身份运行, 把安装目录复制进去, 然后回车. 
再次打开就好了

**Comment by strongant** [comment]
还是不行！
![](http://p1.bpimg.com/4851/eaf6cf18335d2fd0.jpg)

**Comment by ystyle** [comment]
### 以下为手工设置方式

settings.txt
文件应该是这样的：
```
root: D:\Program Files (x86)
arch: 64
proxy: none
originalpath: 
originalversion: 
```

删除用户环境变量： JVMS_HOME, PATH里的JVMS_HOME\bin 和JAVA_HOME\bin
修改系统环境变量：JVMS_HOME 为 `D:\Program Files (x86)\jvms`
JAVA_HOME = C:\Program Files (x86)\jdk
PATH里JVMS_HOME\bin;JAVA_HOME\bin 建议放到最前面。

**Comment by ystyle** [comment]
下个版本已经在写了， 没那么复杂的设置了，全部东西会直接在`jvms init`命令完成， 并支持换源(自己搭建内网的jdk下载服务器)， 但还没写完，估计还要很长一段时间

**Comment by strongant** [comment]
根据你的配置我设置了之后还是有问题，你这个实现思路主要是配置不同的jdk的Path目录，然后动态修改Path中的jdk的目录？

**Comment by ystyle** [comment]
不是这样的， 我的思路是和`nvm-windows`的实现方式是一至的, 
settings.txt 的root字段是jdk存储目录.
JVMS_HOME 是程序内部有读一些安装目录下的数据创建的, 添加`JVMS_HOME/bin`到PATH是为了能在命令行上使用jvms命令. 
JAVA_HOME是固定不变的. 改变jdk是用的软件连接的方式(只支持vista系统及以上,vista的新功能), 更换jdk是直接修改对应软连接(以上例子为: C:\Program Files (x86)\jdk)的目标目录(如果用的是1.7版本在64位系统中目标目录为D:\Program Files (x86)\jvms\v1.7.0_67_x64)
**软连接详细请看linux入门中的软连接或vista中mklink命令**

**Comment by strongant** [comment]
明白了，现在按照你的帮助我配置成功了，谢谢！windows中可以使用软连接还第一次听说，之前不知道，长见识了。

**Comment by strongant** [comment]
谢谢！

**Comment by strongant** [comment]
如果我想添加指定的版本是不是只需要下载相应的版本按照你文件名的规则放到jvms目录下，然后使用jvms use jdk 版本号就可以了？

**Comment by ystyle** [comment]
对的， [详细设置](https://github.com/ystyle/jvms#add-a-local-jdk-version)
