### ISSUE TITLE
Can't switch to Java 1.8

### ISSUE THREAD

**Issue by pavliczandris** [ystyle/jvms#33]
Hi,

I recently downloaded the latest release of jvms ([v2.1.3](https://github.com/ystyle/jvms/releases/tag/v2.1.3)) and I installed 1.8.0_151. When I try to switch to that version, it says that version is not installed.

Looking briefly at the code, I found that it's looking for javac.exe to determine if the version exists or not, and that file is not present for this version.

Any workaround suggestion? Thanks in advance!

**Comment by ystyle** [comment]
try v2.1.4

**Comment by pavliczandris** [comment]
Thanks for the quick response!

I tried v2.1.4 now, and I started over with everything, and now I get an error while downloading:
`
unzip failed: rename C:\Program Files\jvms\download\1.8.0_151_temp C:\Program Files\jvms\store\1.8.0_151: The system cannot find the file specified.
`

It happens with every other version I tried to install.

By the way, I'm using win 11.

**Comment by ystyle** [comment]
Erroneously delete the decompressed jdk file. Now delete the code, can you try again

**Comment by pavliczandris** [comment]
All good, thanks for the fixes!

**Comment by AdrianoCahete** [comment]
Still happens in Win11 on Terminal app, with admin permissions:
```
unzip failed: rename x:\xxx\jvms\download\17.0.6_temp\jdk-17.0.6 x:\xxx\jvms\store\17.0.6: Access is denied.
```

`jvms` says that `unzip` fails, but it's unzip run correctly, just the copy folder that fails.

If I try to move from PS Terminal, with the same user and session, it works:

```
mv x:\xxx\jvms\download\17.0.6_temp\jdk-17.0.6 x:\xxx\jvms\store\17.0.6
```

After that, manual switch works and everything else @ystyle

**Comment by xdhmoore** [comment]
This is happening to me as well on windows in pwsh.exe version 7.5.2 on Windows Terminal in Administrative Mode, trying to install amazon_jdk17.0.6.
