### ISSUE TITLE
建议增加 jdk 1.7 和 1.8 的 x86版本

### ISSUE THREAD

**Issue by JiaFeiX** [ystyle/jvms#5]
因为一些软件的编译（比如LibreOffice ），需要 32位版本的 jdk， 建议增加如上两个版本，谢谢！

**Comment by ystyle** [comment]
上面的都是我本地有的，话说那能找到安全的绿色版jdk?

**Comment by ystyle** [comment]
在csdn找到了， 等下上传。

**Comment by ystyle** [comment]
估计要等到明天了， 网速太慢，2小时内搞不定了。。。。

**Comment by JiaFeiX** [comment]
谢谢！   如何辨别是绿色的jdk呢？   官方安装包解压出来？

**Comment by ystyle** [comment]
顺便说一下，
[添加本地jdk的方法](https://github.com/ystyle/jvms#add-a-local-jdk-version)
[搭建自己内网JDK下载镜像的方法](https://github.com/ystyle/jvms#create-own-local-download-server)
[制作镜像站jdk zip包的方法](https://github.com/ystyle/jvms#create-a-jdk-zip-file)

本地有的jdk版本可以直接复制过去
如果本地上不了网，可以在内网自己弄一个tomcat之类的搞个临时下载站。或者以支持团队内下载。

**Comment by ystyle** [comment]
@JiaFeiX 对就是直接压缩的java_home目录的版本， 不需要安装 。 

你可以看看我上面的， 如果你本地有的版本可以直接放进去（只要把jdk目录直接复制到`jvms/store`目录就好了）

**Comment by ystyle** [comment]
@JiaFeiX 已经添加好了。
