### ISSUE TITLE
The system cannot find the path specified.

### ISSUE THREAD

**Issue by yuf19-2022** [ystyle/jvms#52]
![image](https://github.com/user-attachments/assets/f8727e3e-cd20-4d30-9f7e-e0ab5e5a4210)
![image](https://github.com/user-attachments/assets/e88e60d4-93d1-43f9-afbc-a1aac1d1aec1)

**Comment by ggaier** [comment]
你这个问题解决了吗，我也是同样的问题。我是自己下载的temurin的jdk放到store目录下的

**Comment by ggaier** [comment]
> 你这个问题解决了吗，我也是同样的问题。我是自己下载的temurin的jdk放到store目录下的

原来是没有执行`jvms init`

**Comment by yuf19-2022** [comment]
> > 你这个问题解决了吗，我也是同样的问题。我是自己下载的temurin的jdk放到store目录下的
> 
> 原来是没有执行`jvms init`

Red MI里面竟然好像没有说呀

**Comment by yuf19-2022** [comment]
> > > 你这个问题解决了吗，我也是同样的问题。我是自己下载的temurin的jdk放到store目录下的
> > 
> > 原来是没有执行`jvms init`
> 
> Red MI里面竟然好像没有说呀

看漏了看到了
