### ISSUE TITLE
设置环境变量失败

### ISSUE THREAD

**Issue by 9527dong** [ystyle/jvms#6]
自己用的是Windows10 LTSB版操作系统，使用` v2.0.0 `进行`jvms.exe init`进行设置环境变量。`Java_home`设置正确，但是`jvms.exe`本身的目录没有设置为空，导致下载好jdk后，创建的软连接失败。最后通过手动设置环境解决了。

**Comment by ystyle** [comment]
发现在cmd的system32目录执行命令时，拿到jvms.exe所在的目录是空的， 所以用Cmd时不要在system32目录执行这命令，我想办法修复一下

**Comment by ystyle** [comment]
最新版本的win10 与 golang 1.9编译后无法重现， 已上传重新编译后的版本
