### ISSUE TITLE
JDK is not installed even after the zip is downloaded, command not found

### ISSUE THREAD

**Issue by hirenchauhan2** [ystyle/jvms#7]
OS: Windows 10
CMD as Administrator

![cmd-jvms](https://user-images.githubusercontent.com/8999668/35481943-882b6a32-0453-11e8-9156-fbd506496aaf.png)

**Comment by ystyle** [comment]
you can run `dir . store download`  in `c:\jvms` and show the result?

**Comment by hirenchauhan2** [comment]
I can see that it downloads the JDK zip file, but it fails to extract it in the `C:\Program Files\jdk`. and if there is not `jdk` folder in `C:\Program Files\`, it does not even create that folder, even when the cmd is running with admin permission.

![2018-01-31_00-28-13](https://user-images.githubusercontent.com/8999668/35585373-c051ce1c-061d-11e8-92cf-9536dcec3d74.png)

**Comment by ystyle** [comment]
It seems that the zip file is unpacked error。
you can try this manual: 
1. extract `1.8.0_31.zip`  `to 1.8.0_31`
2. cut `1.8.0_31` folder  to `c:\jvms\store\`
3. run `jvms ls && jvms switch 1.8.0_31`

jvms will do this: 
- `jvms ls` show the folder in `jvms\store`
- `jvms switch xxx` is create a Symbolic link in  `C:\Program Files\jdk` target is `jvms\store\xxx`

**Comment by hirenchauhan2** [comment]
Thank you @ystyle, this worked! 💯  👍
