### ISSUE TITLE
Switch jdk failed, symlink store\1.7 C:\Program Files\jdk: Cannot create a file when that file already exists.

### ISSUE THREAD

**Issue by 9527dong** [ystyle/jvms#8]
windows 10下，使用switch命令无法选择指定的jdk版本。报错 Switch jdk failed, symlink store\1.7 C:\Program Files\jdk: Cannot create a file when that file already exists.这是啥原因了

**Comment by ystyle** [comment]
先删除目录C:\Program Files\jdk， 再看看不是用的管理员权限运行的， 还有就是cmd 不要在默认c:/windows/system32  位置执行这命令。

**Comment by markmclaren** [comment]
Did you run "jvms init"?
